easy_admin:
    entities:
        # List the entity class name you want to manage
        Player:
            class: App\Entity\Player
            form:
                fields:
                    - 'fact'
            disabled_actions: ['edit', 'delete', 'new']
        Draft:
            class: App\Entity\Draft
            disabled_actions: ['edit', 'delete', 'new']
        DraftPick:
            class: App\Entity\DraftPick
            disabled_actions: ['edit', 'delete', 'new']
        Owner:
            class: App\Entity\Owner
            disabled_actions: ['delete', 'edit', 'new']
        Franchise:
            class: App\Entity\Franchise
            disabled_actions: ['delete', 'edit', 'new']
        Trade:
            class: App\Entity\Trade
            disabled_actions: ['edit', 'delete', 'new']
        TradeSide:
            class: App\Entity\TradeSide
            disabled_actions: ['edit', 'delete', 'new']
        TradeSidePlayer:
            class: App\Entity\TradeSidePlayer
            disabled_actions: ['edit', 'delete', 'new']
        TradeSideDraftPick:
            class: App\Entity\TradeSideDraftPick
            disabled_actions: ['edit', 'delete', 'new']
        FranchiseSnapshot:
            class: App\Entity\TradeSideDraftPick
            disabled_actions: ['edit', 'delete', 'new']
        FranchiseSnapshotBestLineupPlayer:
            class: App\Entity\TradeSideDraftPick
            disabled_actions: ['edit', 'delete', 'new']
        FranchiseSnapshotRosterPlayer:
            class: App\Entity\TradeSideDraftPick
            disabled_actions: ['edit', 'delete', 'new']
