easy_admin:
    disabled_actions: ['delete', 'new']
    entities:
        # List the entity class name you want to manage
        Player:
            class: App\Entity\Player
            form:
                fields:
                    - 'fact'
        Draft:
            class: App\Entity\Draft
        DraftPick:
            class: App\Entity\DraftPick
        Owner:
            class: App\Entity\Owner
        Franchise:
            class: App\Entity\Franchise
