version: "3"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=my-secret-pw
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=my-secret-pw